[versions]
compileSdk = "34"
minSdk = "24"
targetSdk = "34"
appCompat = "1.3.1"
core = "1.10.1"
constraintLayout = "2.1.1"
material = "1.9.0"
navigation = "2.6.0"
recyclerView = "1.2.1"
koin = "3.1.2"
room = "2.5.2"
coroutines = "1.5.1"
lifecycle = "2.7.0"
logginginterceptor = "4.9.3"
glide = "4.14.2"
retrofit = "2.9.0"
junit = "4.+"
testExtJunit = "1.1.3"
espresso = "3.4.0"
timber = "5.0.1"
leakcanary = "2.10"
sqlcipher = "4.4.0"
sqlite = "2.4.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core" }
androidx-constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }

material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-navigation-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-dynamicfeature = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigation" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
koin = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compat = { module = "io.insert-koin:koin-android-compat", version.ref = "koin" }
androidx-room-ksp = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logginginterceptor" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-convert-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlcipher" }
androidx-sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "sqlite" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "testExtJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }